obm/app/models.py
from datetime import datetime
from hashlib import md5
from time import time
from flask import current_app
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
import jwt
from app import db, login
# from app.search import add_to_index, remove_from_index, query_index


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    models = db.relationship('Models', backref='author', lazy='dynamic')
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def owned_models(self):
        models = Models.query.filter_by(user_id=self.id)
        return models.order_by(Models.timestamp.desc())


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Models(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    model_name = db.Column(db.String)
    model_target = db.Column(db.String)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    data_path = db.Column(db.String)  # path to data stored in server
    model_path = db.Column(db.String)  # path to model stored in server
    statue = db.Column(db.Boolean, default=False)  # store the statue

    def complete(self):
        self.statue = True

    def __repr__(self):
        return '<Model {}>'.format(self.model_name)

obm/app/model/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FieldList
from flask_uploads import UploadSet, IMAGES
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User


class ModelForm(FlaskForm):
    model_name = StringField(_l('name of model'), validators=[DataRequired()])
    # model_target = StringField(_l('the class you want to model'), validators=[DataRequired()])
    model_targets = FieldList(StringField(validators=[]),
                              label='the class you want to model', min_entries=2)
    add_target = SubmitField(_('Add'))
    remove_target = SubmitField(_('Remove'))
    submit = SubmitField(_l('Submit'))

    def validate(self):
        if not super(ModelForm, self).validate():
            return False
        val_set = set()
        if " " in self.model_name.data:
            self.model_name.errors.append("model name cannot contain ' '[space]")
            return False
        for target in self.model_targets:
            if target.data == "":
                msg = "target cannot be empty"
                self.model_targets.errors.append(msg)
                return False
            if target.data not in val_set:
                val_set.add(target.data)
            else:
                msg = "target cannot be duplicated"
                self.model_targets.errors.append(msg)
                return False
        return True


photos = UploadSet('photos', IMAGES)


class UploadForm(FlaskForm):
    photo = FileField(validators=[
        FileAllowed(photos, 'Only picture available'),
        FileRequired('Not choose any file')])
    submit = SubmitField('Upload')

obm/app/model/__init__.py
from flask import Blueprint

bp = Blueprint('model', __name__)

from app.model import routes

obm/app/model/routes.py
# coding=utf-8
import requests
import os.path as osp
from datetime import datetime
import json
from flask import render_template, flash, redirect, url_for, request, g
from flask_login import current_user, login_required
from flask_babel import _, get_locale
from app import db
from app.model.forms import ModelForm, UploadForm, photos
from app.models import User, Models
from app.model import bp
from config import ServerConfig


@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())


@bp.route('/new_model', methods=['GET', 'POST'])
# @login_required
def new_model():
    if not current_user.is_authenticated:
        flash("You have to login first")
        return render_template('index.html', title=_('Home'))

    form = ModelForm()
    if form.add_target.data:
        form.model_targets.append_entry('')
    elif form.remove_target.data:
        form.model_targets.pop_entry()
    elif request.form and form.validate_on_submit():
        flash("A new model is under construct!")
        targets = ""
        for target in form.model_targets.data:
            targets += target + "#"
        targets = targets[:-1]  # delete the last '#'
        now = datetime.now().strftime("%Y%m%d%H%M")
        data = {'name': form.model_name.data + now, 'targets': targets}
        r = requests.post("http://localhost:9999", data=data)

        flash(r.text)

        model = Models(model_name=form.model_name.data, model_target=targets, author=current_user,
                       model_path=osp.join(ServerConfig.MODEL_PATH, form.model_name.data + now), timestamp=datetime.now())
        db.session.add(model)
        db.session.commit()
        return redirect(url_for('main.index', title="Home"))

    return render_template('model/new_model.html', form=form, title=_('Create_model'))


@bp.route('/detail/<model_id>', methods=['GET', 'POST'])
@login_required
def detail(model_id):
    model = Models.query.filter_by(id=model_id).first()
    if model not in current_user.owned_models():
        flash("You cannot access this model!")
        return redirect(url_for('main.index'))
    form = UploadForm()
    img_name = request.args.get('img_name')
    label = request.args.get('label')
    confidence = request.args.get('confidence')
    if img_name and label and confidence:
        url = photos.url(img_name)
        return render_template('model/detail.html', model=model, title=model.model_name,
                               img_url=url, label=label, confidence=confidence)
    if form.validate_on_submit():
        filename = photos.save(form.photo.data)
        return redirect(url_for('model.recognize', model_id=model.id, img_name=filename))
        # return redirect(url_for('model.detail', model_id=model.id, img_name=filename))
    return render_template('model/detail.html', model=model, title=model.model_name, form=form)


@bp.route('/check/<model_id>', methods=['GET'])
@login_required
def check(model_id):
    model = Models.query.filter_by(id=model_id).first()

    if model not in current_user.owned_models():
        flash("You cannot access this model!")
        return redirect(url_for('main.index'))

    if model.statue:
        return redirect(url_for('model.detail', model_id=model.id))

    data = {"model_path": model.model_path}
    r = requests.post("http://localhost:9999/check", data=data)
    if r.text == "complete":
        model.complete()
        db.session.commit()
        return redirect(url_for('model.detail', model_id=model.id))
    else:
        ts = datetime.now() - model.timestamp
        ts = ts.seconds
        if ts > 30 * 60:  # longer than 30 min
            flash("the model is under construct(if it has been a long time, you may re-build it)")
        else:
            flash("the model is under construct")
        return render_template('model/detail.html', model=model, title=model.model_name)


@bp.route('/recognize/<model_id>', methods=['GET', 'POST'])
@login_required
def recognize(model_id):
    model = Models.query.filter_by(id=model_id).first()
    img_name = request.args.get('img_name')
    if model not in current_user.owned_models():
        flash("You cannot access this model!")
        return redirect(url_for('main.index'))

    data = {"model_path": model.model_path, "img_name": img_name}
    r = requests.post("http://localhost:9998", data=data)
    msg = json.loads(r.text)
    label = msg['label']
    confidence = msg['confidence']
    return redirect(url_for('model.detail', model_id=model.id, img_name=img_name, label=label, confidence=confidence))

obm/app/templates/_model.html
    <tr>
        <td>
            <span class="model{{ model.id }}">{{ model.model_name }}</span>
        </td>
        <td>
            <span class="model{{ model.id }}">{{ model.model_target }}</span>
        </td>
        <td>
            {{ _('%(when)s', when=moment(model.timestamp).format('LLL')) }}
        </td>
        <td>
            <a class="btn btn-info btn-circle" href="{{ url_for('model.check', model_id=model.id)}}">{{ _('Check') }}</a>
        </td>
    </tr>

obm/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Obm{% else %}{{ _('Welcome to Obm') }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Obm</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{ _('Home') }}</a></li>
                    <li><a href="{{ url_for('model.new_model') }}">{{ _('NewModel') }}</a></li>
                </ul>
                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.index') }}">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>
                    {% else %}
                    <!--<li><a href="{{ url_for('main.index', username=current_user.username) }}">{{ _('Profile') }}</a></li>-->
                    <li><a href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("{{ _('Error: Could not contact server.') }}");
            });
        }
    </script>
{% endblock %}

obm/app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    {% if current_user.is_authenticated %}
    <h1>{{ _('Hi, %(username)s! Here are your models', username=current_user.username) }}</h1>
    {% else %}
    <h1> Welcome to obm(One Button Modeling System)!</h1>
    {% endif %}

    <hr>
    {% if models|length > 0 %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-3"> Model Name </th>
                <th class="col-md-3"> Model target </th>
                <th class="col-md-3"> Built time</th>
                <th class="col-md-1"> Statue </th>
            </tr>
        </thead>
        <tbody>
            {% for model in models %}
            {% include '_model.html' %}
            {% endfor %}
        </tbody>
    </table>
    <nav aria-label="...">
            <ul class="pager">
                <li class="previous{% if not prev_url %} disabled{% endif %}">
                    <a href="{{ prev_url or '#' }}">
                        <span aria-hidden="true">&larr;</span> {{ _('Newer models') }}
                    </a>
                </li>
                <li class="next{% if not next_url %} disabled{% endif %}">
                    <a href="{{ next_url or '#' }}">
                        {{ _('Older models') }} <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% else %}
        {% if not current_user.is_authenticated %}
            <span> Login and create your models! </span>
        {% else %}
            <span>
                <a class="btn btn-info active" href="{{ url_for('model.new_model') }}">Start to create your models!
                </a>
            </span>
        {% endif %}
    {% endif %}

{% endblock %}